all:
  children:
    vagrant:
      hosts:
        192.168.56.55:
          ansible_ssh_private_key_file: ~/data/env/jhipster/.vagrant/machines/jhipster/virtualbox/private_key
      vars:
        ansible_user: vagrant
        ansible_python_interpreter: /usr/bin/python3
    aws:
      hosts:
        18.191.107.87:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/data/pem/keyuseast.pem